name: StockingTW
permalink: :year/:month/:day/:title
baseurl: /jekyll-theme-diary

# Your blog's start year and this year, showed in the footer left
# start is optional
start: 2022
now: 2022
 
# Social links showed in the footer
# You just need modify the nickname of github and twitter
link:
  email : chen_t_w@163.com
  github : StockingTW
  twitter : yourname

# Links in the navigation, you can modify both link name and link url
nav:
   Home: "https://github.com/StockingTW/learn2do.github.io"
   Diary: "https://github.com/StockingTW/learn2do.github.io/diary"
   # ANYTHING: any url
   
markdown: kramdown
highlighter: rouge

sass:
  sass_dir: _sass
  style: compressed
